"""initial schema users gyms gym_users

Revision ID: a42b5bb90a8f
Revises: 
Create Date: 2026-06-06 23:31:37.736950

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'a42b5bb90a8f'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Extensión pgvector (idempotente, se necesita en Etapa 3+)
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # Enumeración gym_user_role (idempotente: PG no soporta IF NOT EXISTS para TYPE)
    op.execute(
        "DO $$ BEGIN "
        "    CREATE TYPE gym_user_role AS ENUM ('OPERATOR', 'MANAGER', 'OWNER'); "
        "EXCEPTION "
        "    WHEN duplicate_object THEN NULL; "
        "END $$"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gyms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('is_superadmin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('gym_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gym_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', postgresql.ENUM('OPERATOR', 'MANAGER', 'OWNER', name='gym_user_role', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gym_id', 'user_id', name='uq_gym_user')
    )
    op.create_index(op.f('ix_gym_users_gym_id'), 'gym_users', ['gym_id'], unique=False)
    op.create_index(op.f('ix_gym_users_user_id'), 'gym_users', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gym_users_user_id'), table_name='gym_users')
    op.drop_index(op.f('ix_gym_users_gym_id'), table_name='gym_users')
    op.drop_table('gym_users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('gyms')
    # ### end Alembic commands ###

    # Drop explícito del enum (PG no lo borra junto con la tabla)
    op.execute("DROP TYPE IF EXISTS gym_user_role")

    # NOTA: NO dropeamos la extensión pgvector en downgrade porque podría
    # estar en uso por otras bases de datos del mismo cluster.
